language: go

go:
    - 1.9
    - master

script:
  - go build ./service/main.go
  - go build ./cli/main.go
  - go test ./service/vendor/...
  - go test ./cli/vendor/...

notifications:
  email:
    on_success: change
    on_failure: always
